SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE accounts;
ALTER TABLE accounts ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE bookmarks;
ALTER TABLE bookmarks ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE comments;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE quiz_graded_answers;
ALTER TABLE quiz_graded_answers ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE likes;
ALTER TABLE likes ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE nickname_metadata;

TRUNCATE TABLE pronunciations;
ALTER TABLE pronunciations ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE quiz_metadata;
ALTER TABLE quiz_metadata ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE quiz_options;
ALTER TABLE quiz_options ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE quiz_questions;
ALTER TABLE quiz_questions ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE quizzes;
ALTER TABLE quizzes ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE reports;
ALTER TABLE reports ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE skills;
ALTER TABLE skills ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE today_quizzes;
ALTER TABLE today_quizzes ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE today_quiz_graded_answer;
ALTER TABLE today_quiz_graded_answer ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE today_quiz_options;
ALTER TABLE today_quiz_options ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE word_examples;
ALTER TABLE word_examples ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE word_metadata;
ALTER TABLE word_metadata ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE word_randoms;
ALTER TABLE word_randoms ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE words;
ALTER TABLE words ALTER COLUMN id RESTART WITH 1;


SET REFERENTIAL_INTEGRITY TRUE;
