package com.dnd.spaced.global.exception.code;

public enum AuthErrorCode implements ErrorCode {

    INVALID_TOKEN_EXCEPTION,
    INVALID_BLACKLIST_TOKEN_CONTENT_EXCEPTION,
    FORBIDDEN_INIT_CAREER_INFO_EXCEPTION,
    REFRESH_TOKEN_NOT_FOUND_EXCEPTION,
    EXPIRED_TOKEN_EXCEPTION,
    BLOCKED_TOKEN_EXCEPTION,
    ROTATION_REFRESH_TOKEN_MISMATCH_EXCEPTION,
    NICKNAME_METADATA_NOT_FOUND_EXCEPTION
}
