package com.dnd.spaced.global.exception.code;

public enum QuizErrorCode implements ErrorCode {

    INVALID_QUIZ_CATEGORY_NAME_EXCEPTION,
    INVALID_SUBMITTED_QUIZ_OPTION_INDEX_EXCEPTION,
    INVALID_SUBMIT_ANSWERS_COUNT_EXCEPTION,
    INVALID_QUIZ_OPTION_CONTENT_EXCEPTION,
    INVALID_QUIZ_QUESTION_EXCEPTION,
    INVALID_QUIZ_QUESTION_CONTENT_EXCEPTION,
    INVALID_TODAY_QUIZ_QUESTION_EXCEPTION,
    INVALID_TODAY_QUIZ_QUESTION_CONTENT_EXCEPTION,
    INVALID_SUBMITTED_TODAY_QUIZ_OPTION_INDEX_EXCEPTION,
    INVALID_TODAY_QUIZ_OPTION_CONTENT_EXCEPTION,
    WORD_METADATA_NOT_FOUND_EXCEPTION,
    INVALID_QUIZ_WORD_COUNT_EXCEPTION,
    QUIZ_NOT_FOUND_EXCEPTION,
    TODAY_QUIZ_NOT_FOUND_EXCEPTION,
    QUIZ_CATEGORY_NOT_FOUND_EXCEPTION,
    INVALID_TODAY_QUIZ_WORD_COUNT_EXCEPTION,
    ALREADY_GRADE_QUIZ_EXCEPTION
}
