package com.dnd.spaced.global.exception.code;

public enum WordErrorCode implements ErrorCode {

    INVALID_CATEGORY_NAME,
    INVALID_PRONUNCIATION_CONTENT,
    INVALID_PRONUNCIATION_TYPE_NAME,
    INVALID_WORD_EXAMPLE_CONTENT,
    INVALID_WORD_MEANING,
    INVALID_WORD_NAME,
    WORD_NOT_FOUND,
    UNEXPECTED_UPDATE_WORD_EXAMPLE_COUNT,
    WORD_EXAMPLE_DELETION_NOT_ALLOWED,
    PRONUNCIATION_DELETION_NOT_ALLOWED,
    WORD_METADATA_COUNTER_NOT_FOUND_EXCEPTION,
    WORD_NOT_FOUND_IN_LISTENER_EXCEPTION
}
