name: "Config Request"
description: "프로젝트에 대한 설정 요청"
labels: "Config"
body:
  - type: textarea
    attributes:
      label: 설명
      description: 새로운 설정이 필요한 이유를 작성해 주세요.
      placeholder: 새로운 설정이 필요한 이유를 작성해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 내용
      description: 추가해야 하는 설정에 대한 Tasks를 작성해 주세요.
      placeholder: 추가해야 하는 설정에 대한 Tasks를 작성해 주세요.
    validations:
      required: true
