spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: localhost
      port: 6379

log:
  directory: ./

token:
  access-key: thisistoolargeaccesstokenkeyfordummykeydataforlocal
  refresh-key: thisistoolargerefreshtokenkeyfordummykeydataforlocal
  issuer: localissuer
  access-expired-seconds: 3600
  refresh-expired-seconds: 259200
  access-expired-millis-seconds: 3600000
  refresh-expired-millis-seconds: 259200000

app:
  image:
    path: /home/
  profile:
    nickname:
      adjective:
        - 멋있는
        - 무서운
        - 상큼한
        - 행복한
        - 재빠른
      planet:
        - 수성
        - 금성
        - 지구
        - 화성
        - 목성
        - 토성
        - 천왕성
        - 해왕성
      format: "%s%03d"
    image:
      name:
        - mercury.png
        - venus.png
        - earth.png
        - mars.png
        - jupiter.png
        - saturn.png
        - uranus.png
        - neptune.png
