spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: client-id
            client-secret: client-secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: openid
            client-name: Kakao
            provider: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            issuer-uri: https://kauth.kakao.com

log:
  directory: ./

token:
  access-key: thisistoolargeaccesstokenkeyfordummykeydataforlocal
  refresh-key: thisistoolargerefreshtokenkeyfordummykeydataforlocal
  issuer: localissuer
  access-expired-seconds: 3600
  refresh-expired-seconds: 259200
  access-expired-millis-seconds: 3600000
  refresh-expired-millis-seconds: 259200000

app:
  image:
    path: /home/
  profile:
    nickname:
      adjective:
        - 멋있는
        - 무서운
        - 상큼한
        - 행복한
        - 재빠른
      planet:
        - 수성
        - 금성
        - 지구
        - 화성
        - 목성
        - 토성
        - 천왕성
        - 해왕성
      format: "%s%03d"
    image:
      name:
        - mercury.png
        - venus.png
        - earth.png
        - mars.png
        - jupiter.png
        - saturn.png
        - uranus.png
        - neptune.png
