name: CI for Pull Request with Test

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: ./space-d
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          token: ${{ secrets.REPO_PAT }}

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('space-d/**/*.gradle*', 'space-d/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test with Gradle
        run: ./gradlew jacocoTestCoverage
